// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtq8gH6ONrAZy0rynCjcVxC1miKEScmNs',
    appId: '1:578636434026:web:3dacb8e515d5d7d0975813',
    messagingSenderId: '578636434026',
    projectId: 'nafasauth',
    authDomain: 'nafasauth.firebaseapp.com',
    storageBucket: 'nafasauth.firebasestorage.app',
    measurementId: 'G-8R1NZECW8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXUSC1xU3WL43SZDV5gnPobfSAoVhtF58',
    appId: '1:578636434026:android:89825bef40f3ea86975813',
    messagingSenderId: '578636434026',
    projectId: 'nafasauth',
    storageBucket: 'nafasauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTuPAf1VlOp1SCOm08-Oyr0f0hvGls3u4',
    appId: '1:578636434026:ios:5a0c57072e7a9951975813',
    messagingSenderId: '578636434026',
    projectId: 'nafasauth',
    storageBucket: 'nafasauth.firebasestorage.app',
    iosBundleId: 'com.example.nafas',
  );
}
